// Клиенты Google и MAX без сети: подпись JWT RS256 проверяется открытым ключом, формы запросов совпадают с REST API Sheets/Drive и MAX Bot API.
import assert from 'node:assert/strict';
import {generateKeyPairSync,createVerify} from 'node:crypto';
import {GoogleAuth,Sheets,Drive} from '../bot/payments/google.js';
import {MaxApi,keyboard} from '../bot/payments/max.js';
const {privateKey,publicKey}=generateKeyPairSync('rsa',{modulusLength:2048,privateKeyEncoding:{type:'pkcs8',format:'pem'},publicKeyEncoding:{type:'spki',format:'pem'}});
const calls=[];
const fetchFn=async(url,init)=>{calls.push({url,init});
 if(url.startsWith('https://oauth2'))return new Response(JSON.stringify({access_token:'tok',expires_in:3600}),{status:200});
 if(url.includes(':append'))return new Response(JSON.stringify({updates:{updatedRange:"'Журнал оплат'!A31:H31"}}),{status:200});
 if(url.includes('fields=properties'))return new Response(JSON.stringify({properties:{title:'T'},sheets:[{properties:{sheetId:1,title:'Журнал оплат'}}]}),{status:200});
 return new Response('{}',{status:200});};
const auth=new GoogleAuth({clientEmail:'sa@x.iam.gserviceaccount.com',privateKey,scopes:['s1','s2'],fetch:fetchFn,now:()=>1_700_000_000_000});
const jwt=auth.jwt();const [h,c,sig]=jwt.split('.');
assert.deepEqual(JSON.parse(Buffer.from(h,'base64url')),{alg:'RS256',typ:'JWT'});
const claims=JSON.parse(Buffer.from(c,'base64url'));assert.equal(claims.scope,'s1 s2');assert.equal(claims.exp-claims.iat,3600);assert.equal(claims.aud,'https://oauth2.googleapis.com/token');
assert.equal(createVerify('RSA-SHA256').update(h+'.'+c).verify(publicKey,Buffer.from(sig,'base64url')),true,'подпись проверяется открытым ключом');
assert.equal(await auth.token(),'tok');assert.equal(await auth.token(),'tok');assert.equal(calls.filter(c=>c.url.startsWith('https://oauth2')).length,1,'токен кэшируется');
const sheets=new Sheets(auth,'SID');
const r=await sheets.appendRow('Журнал оплат',[1,'O-01','',2,3,'x','y','z']);
assert.equal(r.row,31);
const ap=calls.at(-1);assert.match(decodeURIComponent(ap.url),/values\/'Журнал оплат'!A:H:append\?valueInputOption=RAW&insertDataOption=INSERT_ROWS/);
assert.equal(ap.init.headers.Authorization,'Bearer tok');assert.deepEqual(JSON.parse(ap.init.body).values,[[1,'O-01','',2,3,'x','y','z']]);
await sheets.copyRowStyle('Журнал оплат',31);
const bu=JSON.parse(calls.at(-1).init.body);
assert.equal(bu.requests.length,2);
assert.deepEqual(bu.requests[0].copyPaste,{source:{sheetId:1,startRowIndex:1,endRowIndex:2,startColumnIndex:0,endColumnIndex:8},destination:{sheetId:1,startRowIndex:30,endRowIndex:31,startColumnIndex:0,endColumnIndex:8},pasteType:'PASTE_FORMAT',pasteOrientation:'NORMAL'});
assert.deepEqual(bu.requests[1].copyPaste.source,{sheetId:1,startRowIndex:1,endRowIndex:2,startColumnIndex:2,endColumnIndex:3});assert.equal(bu.requests[1].copyPaste.pasteType,'PASTE_FORMULA');
const bg=calls.find(c=>c.url.includes('batchGet'))||(await sheets.batchGet(["'A'!A2:P","'B'!A2:H"]),calls.at(-1));
assert.match(bg.url,/valueRenderOption=UNFORMATTED_VALUE&dateTimeRenderOption=SERIAL_NUMBER/);assert.equal((bg.url.match(/ranges=/g)||[]).length,2);
const drive=new Drive(auth);await drive.upload({name:'a.jpg',mimeType:'image/jpeg',buffer:Buffer.from('xx'),folderId:'F'});
const up=calls.at(-1);assert.match(up.url,/upload\/drive\/v3\/files\?uploadType=multipart/);assert.match(up.init.headers['content-type'],/multipart\/related; boundary=/);
assert.match(up.init.body.toString(),/"parents":\["F"\]/);
await drive.list({folderId:'F',nameContains:'__MAX-'});assert.match(new URL(calls.at(-1).url).searchParams.get('q'),/'F' in parents and trashed = false and name contains '__MAX-'/);
// MAX
const mcalls=[];const mfetch=async(url,init)=>{mcalls.push({url,init});return new Response(JSON.stringify({message:{body:{mid:'1'}},updates:[],marker:5}),{status:200});};
const api=new MaxApi('secret-token',{fetch:mfetch});
await api.sendMessage({chatId:-100,text:'hi',attachments:[keyboard([['Оплачено']])]});
assert.equal(mcalls[0].url,'https://platform-api2.max.ru/messages?chat_id=-100');assert.equal(mcalls[0].init.headers.Authorization,'secret-token');
assert.deepEqual(JSON.parse(mcalls[0].init.body),{text:'hi',notify:true,attachments:[{type:'inline_keyboard',payload:{buttons:[[{type:'callback',text:'Оплачено',payload:'Оплачено'}]]}}]});
await api.getUpdates({marker:0,types:['message_created']});assert.equal(mcalls[1].url,'https://platform-api2.max.ru/updates?marker=0&limit=100&timeout=30&types=message_created');
await api.answerCallback('cb1',{notification:'ok'});assert.equal(mcalls[2].url,'https://platform-api2.max.ru/answers?callback_id=cb1');
const bad=new MaxApi('t',{fetch:async()=>new Response(JSON.stringify({code:'verify.token',message:'Invalid'}),{status:401})});
await assert.rejects(bad.getMe(),e=>e.status===401);
console.log('PASS: JWT RS256 подписывается и проверяется, формы запросов Sheets/Drive/MAX верные');
